app:
  name: My app of spring boot config from git repo
  description: Welcome to ${app.name}
  
my:
  greeting: updated Spring Boot from config server specific of git repo
  list: one,two,three

db:
  connection: "{connectionString: 'http://------', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 1200

#this expose everything with * 
management.endpoints.web.exposure.include: "*"
